//write the sub two number and avgrage c ++ programming
    #include <iostream>
    using namespace std;
    int main()
    {
        float num1,num2,sub,avg;
        cout << "enter the first number:-";
        cin >> num1;
        cout <<"enter the second number:-";
        cin >> num2;
        sub =num1- num2;
        avg = sub/2;
        cout <<  "sub =" << sub << "\n";
        cout << "avg =" << avg << "\n";
        return 0;

    }
