//write the program basic
/*#include <iostream>
using namespace std;
int main()
{

    cout <<"c++ is better than c";
    return 0;
}*/
//write the add two number and avgrage c ++ programming
    #include <iostream>
    using namespace std;
    int main()
    {
        float num1,num2,sum,avg;
        cout << "enter the first number:-";
        cin >> num1;
        cout <<"enter the second number:-";
        cin >> num2;
        sum =num1+ num2;
        avg = sum/2;
        cout <<  "sum =" << sum << "\n";
        cout << "avg =" << avg << "\n";
        return 0;

    }
