//write the divison two number and avgrage c ++ programming
    #include <iostream>
    using namespace std;
    int main()
    {
        float num1,num2,div,avg;
        cout << "enter the first number:-";
        cin >> num1;
        cout <<"enter the second number:-";
        cin >> num2;
        div =num1/ num2;
        avg = div/2;
        cout <<  "div =" << div << "\n";
        cout << "avg =" << avg << "\n";
        return 0;

    }
