//write the multply two number and avgrage c ++ programming
    #include <iostream>
    using namespace std;
    int main()
    {
        float num1,num2,mul,avg;
        cout << "enter the first number:-";
        cin >> num1;
        cout <<"enter the second number:-";
        cin >> num2;
        mul =num1* num2;
        avg = mul/2;
        cout <<  "mul =" << mul << "\n";
        cout << "avg =" << avg << "\n";
        return 0;

    }
